---
- name: Installing prometheus alertmanager
  ansible.builtin.include_role:
    name: andrewrothstein.prometheus_installer
  vars:
    prometheus_installer_versions:
      - name: alertmanager
        version: '{{ prometheus_alertmanager_ver }}'
